name: vote_safe
description: A decentralized verification voting system.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.3
  web3dart: ^2.7.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

